### ISSUE TITLE
no manele 👎👎👎

### ISSUE THREAD

**Issue by lazydev1852** [SparXFusion/android_device_realme_RMX1831#5]
tracta-mi-as pula in gura ta ca la remorca in mortii tai de sclava penala ce esti ca-mi rasfrang pula in inima ta si in toate arterele ma-tiistiu sa-mi implant pula in inima ta sa ti-o scot din piept sa fac fatalitate ca la Mortal Kombat futu-te-n gura de latura dreacu penal prost ce esti ca-mi bat pula de gura ta sa zici ca ti-am dat upercutul lui Tyson mormantu ma-tii de muist clapaug , esti uscat in cur mai ceva ca o camila in desert dupa spusele lu tac-tu cand va ardeti in popou in baie baga-mi-as pula in gura lui de fomist si in proteza mortilor ma-tii care i-a scapat lu bunica-ta ca-mi bag pula in iobagia mortilor ma-tii de lesinat ca-mi mananci pula cu mici si bere fac forfota la ma-ta in pizda ma gunoiule trag pula in ochii tai de canalist notoriu sa-ti moara familia la intrare in casa trazniti cu fulgeru de la AC/DC bag pula in tiru ma-tii astazi si maine esti sofer de camion sa-mi sugi pula pe beton da-te-n pula mea de stinghie de om sa sugi pula la toti abonatii ba hepatita umana ce esti nu vezi ca ne batem toti pula de voi aici iti neutralizez pizda aia violata de turci si de daci si de romani caca-m-as pe gura ta de tarfa betiva ce esti sa-mi musti cacatu precum vata de zahar baga-mi-as pula in gura ta de catea in calduri ce esti sa-mi sugi madularu pana iti intra intre buci ca intru in gatu tau cum intra metroul in tunel jgheab de fetita obosita ce esti sa-mi lustruiesti pula mai ceva ca pe totem in gatu ma-tii o exilez pe ma-ta pe insula sa creada ca e in Supravietuitorul sa manance toate ziua pula mea sa castige premiul de curva secolului ma curvo tu foloseste prezervativul data viitoare cand te futi ca poate ramai bortoasa cu gayu ala al tau baga-v-as sloboz in vene si in perfuzie sa va las pe viata paralizati iti dau cu aspiratoru in pizda de muista avortata ce esti sa te desfund in vagin cu peria de la wc

sa-mi bag pula in gatu ma-tii cu ducatu mortilor ma-tii futu-te-n gat de sclifosit obosit sa-mi belesti pula pana faci bataturi in palma futu-ti cactusu care a intrat la ma-ta in cur si i-a facut fisuri anale punea-o-as pe ma-ta in sac s-o transez sa o arunc in dunare in pungi de H&M taranu pulii futu-ti agricultura ma-tii si boii care injuga la ma-ta in vagin sa ii dau la muie de tarfa maiastra cu grad 0 trag pula in ochii tai sa iti fac strabism manca-te-ar canceru si buba neagra de idiot ca o fut pe ma-ta buco anal pisa-te-as in gura de la distanta sa te fac fantana arteziana picura-te-as cu pisat de pe bloc futu-ti faringele ma-tii de redus mi-am bagat pula in familia mortilor vostrii de tarani martalogi ca va pompez cu sloboz pe fata pana ajungeti sa va sugeti coaiele unul altuia de ciuda sa-mi stranutati pe pula in timp ce va fut in gura si in timp ce ma cac sa faceti boala de ficat eu injur de la 11 ani ma lepro crezi ca-s ca voi sa iau dume de pe net ba baga-v-as petarde in sicriu de tigani muisti de nu va extermin mai ceva ca Hitler pe evrei perfora-v-as gaozu cu pula sa ziceti ca mi-am bagat tarnacopu in voi firar mama voastra a dracu de naluci proaste baga-mi-as pula

**Comment by AntoninoScordino** [comment]
o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryur

**Comment by plarfman** [comment]
o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryur

**Comment by lazydev1852** [comment]
> o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuro fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryuri 💪🏿💪🏿💥💥😈😈o fata mia zis buna, putem sex astazi? io nu prea inteleg ca sunt furryur

"Vreau să fut! Îmi place mult să fut. E singura manifestare care e umană: așa. E umană și ea trebuie cu adevărat revendicată și de mine.
Mi-au trecut anii și de-abia acu' mi-am dat seama că pula și pizda sunt cele mai importante organe - mai tari decât Ministrul Justiției; organele de interne, ale SRI-ului; organele prezidențiale. Pula și pizda și coaiele sunt cele mai tari lucruri; sunt și organe, da' organele-s genitale. Și vreau să fut și eu să mă simt bine.
Negrii și-au dat seama demult, americanii la fel - au înaltă știință: au Viagra. Ei au adus-o și aici; și face pula mare. Au... doctorii au descoperit multe panacee universale "care face" pule mari. Pule mari și coaie mari. Lucru care și le... vor să și le revendice femeile.
Acum, pentru că sunt bătrân și sunt la vârsta senectuții, înțelepciunea mea nu-mi depășește organul genital. Eu am capul, cap de pulă! Adică nu-mi trece să am vreo manifestare, vreo știință-n mine. Dacă mi se scoală pula gândesc: vreau pizdă! Vreau între țâțe, vrea în anus să i-o bag, și în multe alea-alea; la muie, în gură să-i bag.
Și vreau să îmi pun bile. De aceea așteptați-mă să-mi pun bile. Zece bile voi pune. Numărul care arată: unu, doi, trei, zero; unu, doi, trei, patru, cinci, șase, șapte, opt, nouă, zece. Se dau numere. Zece numere și cu zero: unsprezece.
Voi fute mai mult ca oricând acum la bătrânețe!"

**Comment by AntoninoScordino** [comment]
BAMBIEL!
Todo comienza cuando no hay nada que hacer
Cuando todo lo que quieres es tener un publico que entretener
Cuando haces algo random
Sin imaginarte que algún día el mundo de tí te estará hablando
Sólo haces lo que te gusta
Y resulta que lo que haces mucha gente lo disfruta
Ingresas a YOUTUBE!!... y creas un canal
Creas un personaje y dejas de ser normal
Miles de LIKES, miles de VISTAS
Viendo tu nombre en las mejores listas
Miles de fans, se hacen MILLONES!!
Se vuelven realidad muchas de tus ILUSIONES!!
Botón de plata, botón de oro
Y la placa de diamante que es el mayor tesoro
Poco lo has logrado y de uno es que te voy hablar yo
Este es el rap de FERNANFLOO!
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CHORIZO!
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CARAJOOO!
Si quieres ver un gameplay matando de la risa
Pues mira fernanfloo... y hazlo deprisa
Fernan el CRACK, Fernan el FAIL
Escucha la voz zukulenta del MMMM YEAH!!!
Me sorprende hasta donde has llegado, de verdad
La gente mira tu canal y dice: OH MY GOD!!
Te pelas, te pasas y a veces la regas
Y es entretenido que juegues GEOMETRY DASH
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CHORIZO!
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CARAJOOO!
Con la rana René, con tu perrito Curly
Goku que no te viola y no es que yo me burle, PERO!
Me mata de la risa tu cara del MEME
Es rara la ocasión en la que no menciones "PENE"
Con tu gorra de Luigi, tu risa desquiciada
Lentes de violador y tu sonrisa de metal
Las cosas que dices cuando "Se te lengua la traba"
Tu cara de locura cuando te desesperás
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CHORIZO!
EL RAP DE FERNANFLOO
El rap de fernanfloo flo flo flo flo
EL RAP DE FERNANFLOO
Si no te gusta andate al CARAJOOO!
Eres un CRACK, lograste lo que pocos han logrado
La gente esta locá, yo igual estoy alocado
Por eso tus locura me parecen divertidas
Vale un chorizo si hay mentes pervertidas
Todo es una locura
Mi personaje también tiene una mente inmadura
Te saludo desde aquí, tu país El Salvador
Espero que prosperes y sigás siendo MEJOR!
