### ISSUE TITLE
rename device tree from vayu

### ISSUE THREAD

**Issue by AntoninoScordino** [SparXFusion/android_device_realme_RMX1831#6]
hello sir pls rename rmx1831 devic tree from vayu for best performance thenask you i want to pley pbugagay at 4021fps with much much heat thanks

**Comment by plarfman** [comment]
he forgot to enable PQ 🤣

**Comment by AntoninoScordino** [comment]
pq disbaled now max perfm thanks @plarfman 😃 😃 😃 😃 😃 😃 😃
